### PR TITLE
Add explicit keepInBounds call to wcm init

### LINKED ISSUE #5: Initialization of CMA-ES mean
Hi,

is the initialization of the mean of CMA-ES expected to be drawn from a standard distribution rather than a uniform one?
See Algorithms.py Line 475
`wcm = (np.random.randn(n, 1) * (u_bound - l_bound)) + l_bound`

The bounds will not be respected in this case, np.random.rand() might be the more appropriated function.

Kind regards,

Raphael

### PR DESCRIPTION
**Pull request by sjvrijn**
This should fix #5.
@reiyan, do you agree this is a valid solution for the issue you raised?

### CODE REVIEW

**Comment by Reiyan** [comment]
Hey @sjvrijn, 

yes and no 😄. I mean it makes sure that the initial starting point of CMA-ES is within the given bounds.
Yet, the point I was trying to make is, that CMA-ES (while in general operating on a multivariate normal distribution) does not sample the initial point in that manner.

As far as I can tell, this happens uniformly. At least when consulting the revised version of [The CMA Evolution Strategy: A Tutorial](https://arxiv.org/pdf/1604.00772.pdf) p.36 line 15 with the MATLAB command: 
```
 xmean = rand(N,1); % objective variables initial point
```
I am not a Matlab specialist by any means, but the [documentation](https://www.mathworks.com/help/matlab/ref/rand.html) of rand(x,y) states that this is an uniform sampling method.

A not really conclusive example is the python implementation of Hansen. At a quick glance, it seems that the constructor of the CMA-ES class requires the starting point (x0) explicitly as an argument of the constructor. However, the examples given there have either a hard-coded starting point or (in one case) are uniformly sampled in the interval [-2, 6]:
```python
>>> bestever = cma.optimization_tools.BestSolution()
>>> for lam in 10 * 2**np.arange(8):  # 10, 20, 40, 80, ..., 10 * 2**7
...     es = cma.CMAEvolutionStrategy(6 - 8 * np.random.rand(4),  # 4-D
...                                   5,  # initial std sigma0
...                                   {'popsize': lam,  # options
...                                    'verb_append': bestever.evalsall})
```
(see https://github.com/CMA-ES/pycma/blob/4390ec35f3bd81925e147fdc781734bb9047e343/cma/evolution_strategy.py#L1225)

However, that is small issue. My main concern was related to the not respected boundaries. The effects of sampling uniformly versus normal distributed with bounds might be minuscule 🤷‍♂️ 

Kind regards,

Raphael

**Comment by sjvrijn** [comment]
@Reiyan Thanks for checking and confirming with the original documentation.
It's been a while since I used this project or worked with CMA-ES, so I wasn't too sharp about this.
I agree that the initial point can and should be sampled uniformly instead.

I'll update this PR to use that solution instead.

Cheers,
Sander

**Comment by Reiyan** [comment]
No worries, thanks for still maintaining this project :)

**Comment by sjvrijn** [comment]
@Reiyan Thanks again for raising the issue and for your patience. I'll now merge this PR to close your issue and will create a new release for PyPI soon (see #8)

**Pull request merged**
